-- ============================================================
-- Daily Credit Spending by Service Type - Setup & Scheduling
-- ============================================================

-- Step 1: Grant necessary privileges
GRANT USAGE ON DATABASE TEST_DB TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
GRANT USAGE ON SCHEMA TEST_DB.PUBLIC TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
GRANT CREATE TABLE ON SCHEMA TEST_DB.PUBLIC TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
GRANT CREATE TASK ON SCHEMA TEST_DB.PUBLIC TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

-- Step 2: Create the table
CREATE TABLE IF NOT EXISTS TEST_DB.PUBLIC.DAILY_CREDIT_SPENDING (
    REPORT_DATE DATE,
    SERVICE_TYPE VARCHAR,
    USER_NAME VARCHAR,
    ROLE_NAME VARCHAR,
    WAREHOUSE_NAME VARCHAR,
    QUERY_TEXT VARCHAR(10000),
    TOTAL_CREDITS NUMBER(20,2),
    PERCENTAGE_OF_TOTAL NUMBER(10,1),
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Step 2b: Alter existing table to add new columns (if table already exists)
ALTER TABLE TEST_DB.PUBLIC.DAILY_CREDIT_SPENDING ADD COLUMN IF NOT EXISTS USER_NAME VARCHAR;
ALTER TABLE TEST_DB.PUBLIC.DAILY_CREDIT_SPENDING ADD COLUMN IF NOT EXISTS ROLE_NAME VARCHAR;
ALTER TABLE TEST_DB.PUBLIC.DAILY_CREDIT_SPENDING ADD COLUMN IF NOT EXISTS WAREHOUSE_NAME VARCHAR;
ALTER TABLE TEST_DB.PUBLIC.DAILY_CREDIT_SPENDING ADD COLUMN IF NOT EXISTS QUERY_TEXT VARCHAR(10000);

-- Step 3: Backfill last 30 days of data
INSERT INTO TEST_DB.PUBLIC.DAILY_CREDIT_SPENDING (REPORT_DATE, SERVICE_TYPE, USER_NAME, ROLE_NAME, WAREHOUSE_NAME, QUERY_TEXT, TOTAL_CREDITS, PERCENTAGE_OF_TOTAL)
SELECT 
    qh.START_TIME::DATE AS report_date,
    mh.SERVICE_TYPE,
    qh.USER_NAME,
    qh.ROLE_NAME,
    qh.WAREHOUSE_NAME,
    LEFT(qh.QUERY_TEXT, 10000) AS QUERY_TEXT,
    ROUND(SUM(qh.CREDITS_USED_CLOUD_SERVICES), 2) AS total_credits,
    ROUND(
        SUM(qh.CREDITS_USED_CLOUD_SERVICES) / 
        NULLIF(SUM(SUM(qh.CREDITS_USED_CLOUD_SERVICES)) OVER (PARTITION BY qh.START_TIME::DATE), 0) * 100, 1
    ) AS percentage_of_total
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY qh
LEFT JOIN (
    SELECT DISTINCT NAME, SERVICE_TYPE
    FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
    WHERE SERVICE_TYPE = 'WAREHOUSE_METERING'
) mh ON qh.WAREHOUSE_NAME = mh.NAME
WHERE qh.START_TIME >= DATEADD(DAY, -30, CURRENT_DATE())
    AND qh.START_TIME < CURRENT_DATE()
    AND qh.WAREHOUSE_NAME IS NOT NULL
GROUP BY qh.START_TIME::DATE, mh.SERVICE_TYPE, qh.USER_NAME, qh.ROLE_NAME, qh.WAREHOUSE_NAME, LEFT(qh.QUERY_TEXT, 10000)
ORDER BY report_date DESC, total_credits DESC;

-- Step 4: Create daily task (runs at 6 AM UTC, inserts previous day's data)
CREATE OR REPLACE TASK TEST_DB.PUBLIC.DAILY_CREDIT_SPENDING_TASK
    WAREHOUSE = INTELLIGENCE_WH
    SCHEDULE = 'USING CRON 0 6 * * * UTC'
AS
INSERT INTO TEST_DB.PUBLIC.DAILY_CREDIT_SPENDING (REPORT_DATE, SERVICE_TYPE, USER_NAME, ROLE_NAME, WAREHOUSE_NAME, QUERY_TEXT, TOTAL_CREDITS, PERCENTAGE_OF_TOTAL)
SELECT 
    qh.START_TIME::DATE AS report_date,
    mh.SERVICE_TYPE,
    qh.USER_NAME,
    qh.ROLE_NAME,
    qh.WAREHOUSE_NAME,
    LEFT(qh.QUERY_TEXT, 10000) AS QUERY_TEXT,
    ROUND(SUM(qh.CREDITS_USED_CLOUD_SERVICES), 2) AS total_credits,
    ROUND(
        SUM(qh.CREDITS_USED_CLOUD_SERVICES) / 
        NULLIF(SUM(SUM(qh.CREDITS_USED_CLOUD_SERVICES)) OVER (PARTITION BY qh.START_TIME::DATE), 0) * 100, 1
    ) AS percentage_of_total
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY qh
LEFT JOIN (
    SELECT DISTINCT NAME, SERVICE_TYPE
    FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
    WHERE SERVICE_TYPE = 'WAREHOUSE_METERING'
) mh ON qh.WAREHOUSE_NAME = mh.NAME
WHERE qh.START_TIME >= DATEADD(DAY, -1, CURRENT_DATE())
    AND qh.START_TIME < CURRENT_DATE()
    AND qh.WAREHOUSE_NAME IS NOT NULL
    AND qh.START_TIME::DATE NOT IN (SELECT DISTINCT REPORT_DATE FROM TEST_DB.PUBLIC.DAILY_CREDIT_SPENDING)
GROUP BY qh.START_TIME::DATE, mh.SERVICE_TYPE, qh.USER_NAME, qh.ROLE_NAME, qh.WAREHOUSE_NAME, LEFT(qh.QUERY_TEXT, 10000);

-- Step 5: Resume the task
ALTER TASK TEST_DB.PUBLIC.DAILY_CREDIT_SPENDING_TASK RESUME;

-- Step 6: Verify data
SELECT * FROM TEST_DB.PUBLIC.DAILY_CREDIT_SPENDING ORDER BY REPORT_DATE DESC, TOTAL_CREDITS DESC;

SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_SNOWSIGHT_USAGE_HISTORY;